# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xilinx_prj/xilinx_Etherent/xtg_ethernet_ex/xtg_ex/xtg_ex.srcs/sources_1/ip/axi_10g_ethernet/axi_10g_ethernet.xci
# IP: The module: 'axi_10g_ethernet' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/xilinx_prj/xilinx_Etherent/xtg_ethernet_ex/xtg_ex/xtg_ex.srcs/sources_1/ip/axi_10g_ethernet/bd_0/bd_9a86.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9a86 || ORIG_REF_NAME==bd_9a86} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_Etherent/xtg_ethernet_ex/xtg_ex/xtg_ex.srcs/sources_1/ip/axi_10g_ethernet/bd_0/ip/ip_0/bd_9a86_xmac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9a86_xmac_0 || ORIG_REF_NAME==bd_9a86_xmac_0} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_Etherent/xtg_ethernet_ex/xtg_ex/xtg_ex.srcs/sources_1/ip/axi_10g_ethernet/bd_0/ip/ip_1/bd_9a86_xpcs_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9a86_xpcs_0 || ORIG_REF_NAME==bd_9a86_xpcs_0} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_Etherent/xtg_ethernet_ex/xtg_ex/xtg_ex.srcs/sources_1/ip/axi_10g_ethernet/bd_0/ip/ip_2/bd_9a86_prtad_driver_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9a86_prtad_driver_0 || ORIG_REF_NAME==bd_9a86_prtad_driver_0} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_Etherent/xtg_ethernet_ex/xtg_ex/xtg_ex.srcs/sources_1/ip/axi_10g_ethernet/bd_0/ip/ip_3/bd_9a86_dcm_locked_driver_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9a86_dcm_locked_driver_0 || ORIG_REF_NAME==bd_9a86_dcm_locked_driver_0} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_Etherent/xtg_ethernet_ex/xtg_ex/xtg_ex.srcs/sources_1/ip/axi_10g_ethernet/bd_0/ip/ip_4/bd_9a86_pma_pmd_type_driver_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9a86_pma_pmd_type_driver_0 || ORIG_REF_NAME==bd_9a86_pma_pmd_type_driver_0} -quiet] -quiet

# XDC: d:/xilinx_prj/xilinx_Etherent/xtg_ethernet_ex/xtg_ex/xtg_ex.srcs/sources_1/ip/axi_10g_ethernet/synth/axi_10g_ethernet_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_10g_ethernet'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/xilinx_prj/xilinx_Etherent/xtg_ethernet_ex/xtg_ex/xtg_ex.srcs/sources_1/ip/axi_10g_ethernet/bd_0/bd_9a86_ooc.xdc

# IP: d:/xilinx_prj/xilinx_Etherent/xtg_ethernet_ex/xtg_ex/xtg_ex.srcs/sources_1/ip/axi_10g_ethernet/axi_10g_ethernet.xci
# IP: The module: 'axi_10g_ethernet' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/xilinx_prj/xilinx_Etherent/xtg_ethernet_ex/xtg_ex/xtg_ex.srcs/sources_1/ip/axi_10g_ethernet/bd_0/bd_9a86.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9a86 || ORIG_REF_NAME==bd_9a86} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_Etherent/xtg_ethernet_ex/xtg_ex/xtg_ex.srcs/sources_1/ip/axi_10g_ethernet/bd_0/ip/ip_0/bd_9a86_xmac_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9a86_xmac_0 || ORIG_REF_NAME==bd_9a86_xmac_0} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_Etherent/xtg_ethernet_ex/xtg_ex/xtg_ex.srcs/sources_1/ip/axi_10g_ethernet/bd_0/ip/ip_1/bd_9a86_xpcs_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9a86_xpcs_0 || ORIG_REF_NAME==bd_9a86_xpcs_0} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_Etherent/xtg_ethernet_ex/xtg_ex/xtg_ex.srcs/sources_1/ip/axi_10g_ethernet/bd_0/ip/ip_2/bd_9a86_prtad_driver_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9a86_prtad_driver_0 || ORIG_REF_NAME==bd_9a86_prtad_driver_0} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_Etherent/xtg_ethernet_ex/xtg_ex/xtg_ex.srcs/sources_1/ip/axi_10g_ethernet/bd_0/ip/ip_3/bd_9a86_dcm_locked_driver_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9a86_dcm_locked_driver_0 || ORIG_REF_NAME==bd_9a86_dcm_locked_driver_0} -quiet] -quiet

# IP: d:/xilinx_prj/xilinx_Etherent/xtg_ethernet_ex/xtg_ex/xtg_ex.srcs/sources_1/ip/axi_10g_ethernet/bd_0/ip/ip_4/bd_9a86_pma_pmd_type_driver_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9a86_pma_pmd_type_driver_0 || ORIG_REF_NAME==bd_9a86_pma_pmd_type_driver_0} -quiet] -quiet

# XDC: d:/xilinx_prj/xilinx_Etherent/xtg_ethernet_ex/xtg_ex/xtg_ex.srcs/sources_1/ip/axi_10g_ethernet/synth/axi_10g_ethernet_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_10g_ethernet'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/xilinx_prj/xilinx_Etherent/xtg_ethernet_ex/xtg_ex/xtg_ex.srcs/sources_1/ip/axi_10g_ethernet/bd_0/bd_9a86_ooc.xdc
