set_property SRC_FILE_INFO {cfile:E:/xilinx_ETH/eth_lab1/Ethernet/xtg_ex/xtg_ex.srcs/constrs_1/new/physical.xdc rfile:../../../xtg_ex.srcs/constrs_1/new/physical.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:E:/xilinx_ETH/eth_lab1/Ethernet/xtg_ex/xtg_ex.srcs/constrs_1/new/timing.xdc rfile:../../../xtg_ex.srcs/constrs_1/new/timing.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB7 [get_ports rst_n]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB8 [get_ports {led[0]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA8 [get_ports {led[1]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC9 [get_ports {led[2]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB9 [get_ports {led[3]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB12 [get_ports push_button]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G8 [get_ports sfp_refclkp]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G4 [get_ports sfp_rxp]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y20 [get_ports sfp_tx_disable]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list mac_subsystem/inst/xpcs/inst/ten_gig_eth_pcs_pma_shared_clock_reset_block/coreclk_out]]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {mac_tx_axis_tkeep[0]} {mac_tx_axis_tkeep[1]} {mac_tx_axis_tkeep[2]} {mac_tx_axis_tkeep[3]} {mac_tx_axis_tkeep[4]} {mac_tx_axis_tkeep[5]} {mac_tx_axis_tkeep[6]} {mac_tx_axis_tkeep[7]}]]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {udp_rx_axis_tdata[0]} {udp_rx_axis_tdata[1]} {udp_rx_axis_tdata[2]} {udp_rx_axis_tdata[3]} {udp_rx_axis_tdata[4]} {udp_rx_axis_tdata[5]} {udp_rx_axis_tdata[6]} {udp_rx_axis_tdata[7]} {udp_rx_axis_tdata[8]} {udp_rx_axis_tdata[9]} {udp_rx_axis_tdata[10]} {udp_rx_axis_tdata[11]} {udp_rx_axis_tdata[12]} {udp_rx_axis_tdata[13]} {udp_rx_axis_tdata[14]} {udp_rx_axis_tdata[15]} {udp_rx_axis_tdata[16]} {udp_rx_axis_tdata[17]} {udp_rx_axis_tdata[18]} {udp_rx_axis_tdata[19]} {udp_rx_axis_tdata[20]} {udp_rx_axis_tdata[21]} {udp_rx_axis_tdata[22]} {udp_rx_axis_tdata[23]} {udp_rx_axis_tdata[24]} {udp_rx_axis_tdata[25]} {udp_rx_axis_tdata[26]} {udp_rx_axis_tdata[27]} {udp_rx_axis_tdata[28]} {udp_rx_axis_tdata[29]} {udp_rx_axis_tdata[30]} {udp_rx_axis_tdata[31]} {udp_rx_axis_tdata[32]} {udp_rx_axis_tdata[33]} {udp_rx_axis_tdata[34]} {udp_rx_axis_tdata[35]} {udp_rx_axis_tdata[36]} {udp_rx_axis_tdata[37]} {udp_rx_axis_tdata[38]} {udp_rx_axis_tdata[39]} {udp_rx_axis_tdata[40]} {udp_rx_axis_tdata[41]} {udp_rx_axis_tdata[42]} {udp_rx_axis_tdata[43]} {udp_rx_axis_tdata[44]} {udp_rx_axis_tdata[45]} {udp_rx_axis_tdata[46]} {udp_rx_axis_tdata[47]} {udp_rx_axis_tdata[48]} {udp_rx_axis_tdata[49]} {udp_rx_axis_tdata[50]} {udp_rx_axis_tdata[51]} {udp_rx_axis_tdata[52]} {udp_rx_axis_tdata[53]} {udp_rx_axis_tdata[54]} {udp_rx_axis_tdata[55]} {udp_rx_axis_tdata[56]} {udp_rx_axis_tdata[57]} {udp_rx_axis_tdata[58]} {udp_rx_axis_tdata[59]} {udp_rx_axis_tdata[60]} {udp_rx_axis_tdata[61]} {udp_rx_axis_tdata[62]} {udp_rx_axis_tdata[63]}]]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {udp_tx_axis_tdata[0]} {udp_tx_axis_tdata[1]} {udp_tx_axis_tdata[2]} {udp_tx_axis_tdata[3]} {udp_tx_axis_tdata[4]} {udp_tx_axis_tdata[5]} {udp_tx_axis_tdata[6]} {udp_tx_axis_tdata[7]} {udp_tx_axis_tdata[8]} {udp_tx_axis_tdata[9]} {udp_tx_axis_tdata[10]} {udp_tx_axis_tdata[11]} {udp_tx_axis_tdata[12]} {udp_tx_axis_tdata[13]} {udp_tx_axis_tdata[14]} {udp_tx_axis_tdata[15]} {udp_tx_axis_tdata[16]} {udp_tx_axis_tdata[17]} {udp_tx_axis_tdata[18]} {udp_tx_axis_tdata[19]} {udp_tx_axis_tdata[20]} {udp_tx_axis_tdata[21]} {udp_tx_axis_tdata[22]} {udp_tx_axis_tdata[23]} {udp_tx_axis_tdata[24]} {udp_tx_axis_tdata[25]} {udp_tx_axis_tdata[26]} {udp_tx_axis_tdata[27]} {udp_tx_axis_tdata[28]} {udp_tx_axis_tdata[29]} {udp_tx_axis_tdata[30]} {udp_tx_axis_tdata[31]} {udp_tx_axis_tdata[32]} {udp_tx_axis_tdata[33]} {udp_tx_axis_tdata[34]} {udp_tx_axis_tdata[35]} {udp_tx_axis_tdata[36]} {udp_tx_axis_tdata[37]} {udp_tx_axis_tdata[38]} {udp_tx_axis_tdata[39]} {udp_tx_axis_tdata[40]} {udp_tx_axis_tdata[41]} {udp_tx_axis_tdata[42]} {udp_tx_axis_tdata[43]} {udp_tx_axis_tdata[44]} {udp_tx_axis_tdata[45]} {udp_tx_axis_tdata[46]} {udp_tx_axis_tdata[47]} {udp_tx_axis_tdata[48]} {udp_tx_axis_tdata[49]} {udp_tx_axis_tdata[50]} {udp_tx_axis_tdata[51]} {udp_tx_axis_tdata[52]} {udp_tx_axis_tdata[53]} {udp_tx_axis_tdata[54]} {udp_tx_axis_tdata[55]} {udp_tx_axis_tdata[56]} {udp_tx_axis_tdata[57]} {udp_tx_axis_tdata[58]} {udp_tx_axis_tdata[59]} {udp_tx_axis_tdata[60]} {udp_tx_axis_tdata[61]} {udp_tx_axis_tdata[62]} {udp_tx_axis_tdata[63]}]]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {mac_rx_axis_tkeep[0]} {mac_rx_axis_tkeep[1]} {mac_rx_axis_tkeep[2]} {mac_rx_axis_tkeep[3]} {mac_rx_axis_tkeep[4]} {mac_rx_axis_tkeep[5]} {mac_rx_axis_tkeep[6]} {mac_rx_axis_tkeep[7]}]]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {mac_rx_axis_tdata[0]} {mac_rx_axis_tdata[1]} {mac_rx_axis_tdata[2]} {mac_rx_axis_tdata[3]} {mac_rx_axis_tdata[4]} {mac_rx_axis_tdata[5]} {mac_rx_axis_tdata[6]} {mac_rx_axis_tdata[7]} {mac_rx_axis_tdata[8]} {mac_rx_axis_tdata[9]} {mac_rx_axis_tdata[10]} {mac_rx_axis_tdata[11]} {mac_rx_axis_tdata[12]} {mac_rx_axis_tdata[13]} {mac_rx_axis_tdata[14]} {mac_rx_axis_tdata[15]} {mac_rx_axis_tdata[16]} {mac_rx_axis_tdata[17]} {mac_rx_axis_tdata[18]} {mac_rx_axis_tdata[19]} {mac_rx_axis_tdata[20]} {mac_rx_axis_tdata[21]} {mac_rx_axis_tdata[22]} {mac_rx_axis_tdata[23]} {mac_rx_axis_tdata[24]} {mac_rx_axis_tdata[25]} {mac_rx_axis_tdata[26]} {mac_rx_axis_tdata[27]} {mac_rx_axis_tdata[28]} {mac_rx_axis_tdata[29]} {mac_rx_axis_tdata[30]} {mac_rx_axis_tdata[31]} {mac_rx_axis_tdata[32]} {mac_rx_axis_tdata[33]} {mac_rx_axis_tdata[34]} {mac_rx_axis_tdata[35]} {mac_rx_axis_tdata[36]} {mac_rx_axis_tdata[37]} {mac_rx_axis_tdata[38]} {mac_rx_axis_tdata[39]} {mac_rx_axis_tdata[40]} {mac_rx_axis_tdata[41]} {mac_rx_axis_tdata[42]} {mac_rx_axis_tdata[43]} {mac_rx_axis_tdata[44]} {mac_rx_axis_tdata[45]} {mac_rx_axis_tdata[46]} {mac_rx_axis_tdata[47]} {mac_rx_axis_tdata[48]} {mac_rx_axis_tdata[49]} {mac_rx_axis_tdata[50]} {mac_rx_axis_tdata[51]} {mac_rx_axis_tdata[52]} {mac_rx_axis_tdata[53]} {mac_rx_axis_tdata[54]} {mac_rx_axis_tdata[55]} {mac_rx_axis_tdata[56]} {mac_rx_axis_tdata[57]} {mac_rx_axis_tdata[58]} {mac_rx_axis_tdata[59]} {mac_rx_axis_tdata[60]} {mac_rx_axis_tdata[61]} {mac_rx_axis_tdata[62]} {mac_rx_axis_tdata[63]}]]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {mac_tx_axis_tdata[0]} {mac_tx_axis_tdata[1]} {mac_tx_axis_tdata[2]} {mac_tx_axis_tdata[3]} {mac_tx_axis_tdata[4]} {mac_tx_axis_tdata[5]} {mac_tx_axis_tdata[6]} {mac_tx_axis_tdata[7]} {mac_tx_axis_tdata[8]} {mac_tx_axis_tdata[9]} {mac_tx_axis_tdata[10]} {mac_tx_axis_tdata[11]} {mac_tx_axis_tdata[12]} {mac_tx_axis_tdata[13]} {mac_tx_axis_tdata[14]} {mac_tx_axis_tdata[15]} {mac_tx_axis_tdata[16]} {mac_tx_axis_tdata[17]} {mac_tx_axis_tdata[18]} {mac_tx_axis_tdata[19]} {mac_tx_axis_tdata[20]} {mac_tx_axis_tdata[21]} {mac_tx_axis_tdata[22]} {mac_tx_axis_tdata[23]} {mac_tx_axis_tdata[24]} {mac_tx_axis_tdata[25]} {mac_tx_axis_tdata[26]} {mac_tx_axis_tdata[27]} {mac_tx_axis_tdata[28]} {mac_tx_axis_tdata[29]} {mac_tx_axis_tdata[30]} {mac_tx_axis_tdata[31]} {mac_tx_axis_tdata[32]} {mac_tx_axis_tdata[33]} {mac_tx_axis_tdata[34]} {mac_tx_axis_tdata[35]} {mac_tx_axis_tdata[36]} {mac_tx_axis_tdata[37]} {mac_tx_axis_tdata[38]} {mac_tx_axis_tdata[39]} {mac_tx_axis_tdata[40]} {mac_tx_axis_tdata[41]} {mac_tx_axis_tdata[42]} {mac_tx_axis_tdata[43]} {mac_tx_axis_tdata[44]} {mac_tx_axis_tdata[45]} {mac_tx_axis_tdata[46]} {mac_tx_axis_tdata[47]} {mac_tx_axis_tdata[48]} {mac_tx_axis_tdata[49]} {mac_tx_axis_tdata[50]} {mac_tx_axis_tdata[51]} {mac_tx_axis_tdata[52]} {mac_tx_axis_tdata[53]} {mac_tx_axis_tdata[54]} {mac_tx_axis_tdata[55]} {mac_tx_axis_tdata[56]} {mac_tx_axis_tdata[57]} {mac_tx_axis_tdata[58]} {mac_tx_axis_tdata[59]} {mac_tx_axis_tdata[60]} {mac_tx_axis_tdata[61]} {mac_tx_axis_tdata[62]} {mac_tx_axis_tdata[63]}]]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {udp_tx_axis_tkeep[0]} {udp_tx_axis_tkeep[1]} {udp_tx_axis_tkeep[2]} {udp_tx_axis_tkeep[3]} {udp_tx_axis_tkeep[4]} {udp_tx_axis_tkeep[5]} {udp_tx_axis_tkeep[6]} {udp_tx_axis_tkeep[7]}]]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {udp_rx_axis_tkeep[0]} {udp_rx_axis_tkeep[1]} {udp_rx_axis_tkeep[2]} {udp_rx_axis_tkeep[3]} {udp_rx_axis_tkeep[4]} {udp_rx_axis_tkeep[5]} {udp_rx_axis_tkeep[6]} {udp_rx_axis_tkeep[7]}]]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list mac_rx_axis_tlast]]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list mac_rx_axis_tusr]]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list mac_rx_axis_tvalid]]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list mac_tx_axis_tlast]]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list mac_tx_axis_tready]]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list mac_tx_axis_tvalid]]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list udp_rx_axis_tlast]]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list udp_rx_axis_tusr]]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list udp_rx_axis_tvalid]]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list udp_tx_axis_tlast]]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list udp_tx_axis_tready]]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list udp_tx_axis_tvalid]]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets coreclk]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -name async_clk0 -asynchronous -group [get_clocks sfp_refclkp] -group [get_clocks mac_subsystem/inst/xpcs/inst/ten_gig_eth_pcs_pma_block_i/gt0_gtwizard_10gbaser_multi_gt_i/gt0_gtwizard_10gbaser_i/gtxe2_i/RXOUTCLK]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -name async_clk1 -asynchronous -group [get_clocks mac_subsystem/inst/xpcs/inst/ten_gig_eth_pcs_pma_block_i/gt0_gtwizard_10gbaser_multi_gt_i/gt0_gtwizard_10gbaser_i/gtxe2_i/TXOUTCLK] -group [get_clocks sfp_refclkp]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks -of_objects [get_pins clk/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks sfp_refclkp]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_clocks mac_subsystem/inst/xpcs/inst/ten_gig_eth_pcs_pma_block_i/gt0_gtwizard_10gbaser_multi_gt_i/gt0_gtwizard_10gbaser_i/gtxe2_i/RXOUTCLK] -to [get_clocks mac_subsystem/inst/xpcs/inst/ten_gig_eth_pcs_pma_block_i/gt0_gtwizard_10gbaser_multi_gt_i/gt0_gtwizard_10gbaser_i/gtxe2_i/RXOUTCLK] 2
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold -from [get_clocks mac_subsystem/inst/xpcs/inst/ten_gig_eth_pcs_pma_block_i/gt0_gtwizard_10gbaser_multi_gt_i/gt0_gtwizard_10gbaser_i/gtxe2_i/RXOUTCLK] -to [get_clocks mac_subsystem/inst/xpcs/inst/ten_gig_eth_pcs_pma_block_i/gt0_gtwizard_10gbaser_multi_gt_i/gt0_gtwizard_10gbaser_i/gtxe2_i/RXOUTCLK] 1
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks sfp_refclkp] -to [get_clocks -of_objects [get_pins clk/inst/mmcm_adv_inst/CLKOUT0]] 8.000
